[package]
name = "ffi-attributes"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0.21" }
proc-macro2 = { version = "1.0.43" }
syn = { version = "1.0.99", features = ["full", "extra-traits"] }