[package]
name = "doublets"
version = "0.5.0"
edition = "2021"
rust-version = "1.85"
authors = [
    "uselessgoddess",
    "Linksplatform Team <linksplatformtechnologies@gmail.com>"
]
categories = [
    "database-implementations",
]
keywords = [
    "associative", "doublets", "db",
]
readme = "../README.md"
license = "Unlicense"
repository = "https://github.com/linksplatform/doublets-rs"
homepage = "https://github.com/linksplatform/doublets-rs"
description = """
Doublets (links) data structure implementation.
"""

[dependencies]
tap = "1"
cfg-if = "1"
thiserror = "2"
leak_slice = "0.2"
# platform
num = { package = "platform-num", version = "0.8.0" }
data = { package = "platform-data", version = "2.0.0" }
mem = { package = "platform-mem", version = "0.3.0" }
trees = { package = "platform-trees", version = "0.3.4" }
# optional
smallvec = { version = "1", features = ["union"], optional = true }
rayon = { version = "1", optional = true }

[features]
mem = []
num = []
data = []
more-inline = []
small-search = ["smallvec"]
platform = ["mem", "num", "data"]

default = ["platform"]
full = ["platform", "rayon", "small-search"]

[dev-dependencies]
tap = "1"
rand = "0.8"
criterion = "0.5"
mimalloc = { version = "0.1", default-features = false }
tinyvec = { version = "1", features = ["alloc"] }
smallvec = { version = "1" }
static_assertions = "1"

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
too_many_lines = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "allow"
missing_const_for_fn = "allow"
needless_pass_by_value = "allow"
comparison_chain = "allow"

[profile.release]
lto = true
codegen-units = 1
strip = true

[[bench]]
name = "iter"
harness = false
